tasks:
  - init: |
      export AIRFLOW_HOME=~/airflow
      pip install --upgrade pip wheel setuptools
      pip install apache-airflow
      airflow db init
      
  - command: |
      nohup airflow webserver -p 8080 &
      nohup airflow scheduler &
      airflow users  create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin
  

vscode:
  extensions:
    - ms-python.python